// jules/llm/llm_interface.go
package llm

// FormInputContext provides details about a specific input field discovered on a form.
type FormInputContext struct {
	Name           string            // Name of the input field
	Type           string            // Type of input (e.g., text, hidden, textarea, select)
	CurrentValue   string            // Default or current value of the input
	Location       string            // Where the input is found (e.g., 'query', 'body-form', 'json-body', 'path')
	HtmlContext    string            // e.g., 'input_value', 'attribute_name', 'js_variable', 'html_comment'
	DetectedFormat string            // e.g., 'email', 'date', 'free_text', 'numeric_id'
	FormAction     string            // The action URL of the form
	FormMethod     string            // The method of the form (GET, POST)
	AdditionalParams map[string]string // Other parameters in the same form/request
}

// LLMRequest encapsulates the data sent to the LLM for a specific task.
type LLMRequest struct {
	TaskType        string             // e.g., "payload_generation", "context_analysis", "vulnerability_assessment"
	InputContext    FormInputContext   // Context of the input field being targeted
	ScanType        string             // Specific vulnerability class to target (e.g., "xss", "sqli", "ssrf")
	KnowledgeBaseHits []string         // Relevant snippets from KB lookups
	PreviousAttempts  []string         // Payloads previously tried for this input (if any)
	MaxTokens       int                // Max tokens for the LLM to generate
}

// LLMPayloadResponse contains payloads generated by the LLM.
type LLMPayloadResponse struct {
	GeneratedPayloads []string // A list of suggested payloads
	ConfidenceScores  []float64 // Optional: confidence for each payload
	Rationale         string    // Optional: LLM's reasoning
}

// LLMAnalysisResponse contains context or vulnerability analysis from the LLM.
type LLMAnalysisResponse struct {
	InputClassification map[string]string // e.g., "data_type": "user_supplied_text", "sensitivity": "high"
	PotentialVulns      []string          // e.g., ["SQLi", "XSS-reflected"]
	Confidence          float64
	Rationale           string
}

// JulesLLM defines the interface for interacting with the Qwen3-8B-AWQ model.
// Implementations will handle the specifics of model loading, prompting, and parsing.
type JulesLLM interface {
	// Initialize loads the LLM model and prepares it for use.
	// configPath might point to model weights, API endpoints (if run as a separate service), etc.
	Initialize(configPath string) error

	// AnalyzeInputContext uses the LLM to understand the context of a given form input.
	AnalyzeInputContext(req LLMRequest) (*LLMAnalysisResponse, error)

	// GeneratePayloads uses the LLM to generate security testing payloads.
	GeneratePayloads(req LLMRequest) (*LLMPayloadResponse, error)

	// RefineWithKnowledge uses the LLM to process info from the knowledge base
	// and potentially update its strategies or suggest new tests.
	// QueryResult is the text back from the KB, originalContext is what prompted the KB lookup.
	RefineWithKnowledge(queryResult string, originalContext LLMRequest) (*LLMPayloadResponse, error) // Or a more general "RefinementResponse"

	// Name returns the name of the LLM model being used.
	Name() string
}
